data:extend({
        {
            type = "bool-setting",
            name = "add-larger-warehouses",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "add-reloader",
            setting_type = "startup",
            default_value = false,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "add-unloader",
            setting_type = "startup",
            default_value = false,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "inserter-unloader",
            setting_type = "startup",
            default_value = false,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "block-stations",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "enable-deadlock-alert-sound",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
        {
            type = "bool-setting",
            name = "enable-nopath-alert-sound",
            setting_type = "startup",
            default_value = true,
            order = "r",
        },
})
